# This template uses the java:8 docker image because there isn't any
# official Gradle image at this moment
#
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: java:8

build:
  stage: build
  script:
     - ./gradlew clean build

test:
  stage: test
  script:
     - ./gradlew test
