# This template uses the java:8 docker image because there isn't any
# official Gradle image at this moment
#
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: java:8

# Make the gradle wrapper executable. This essentially downloads a copy of
# Gradle to build the project with.
# https://docs.gradle.org/current/userguide/gradle_wrapper.html
# It is expected that any modern gradle project has a wrapper
before_script:
    - chmod +x allocation/gradlew

cache:
  paths:
     - allocation/gradle/wrapper

build:
  stage: build
  script:
     - allocation/gradlew assemble

test:
  stage: test
  script:
     - allocation/gradlew check
